# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f06ccd51d3cf551353b5e8e3329d789bf3aab90db027532e2c19e94f8d739066fd46c0e1fe96c6d9019d5eff03362bec39e7a2f156ea3f8614e2fd99ca0c15b

test:
  secret_key_base: 22e79582e6c016c73abc05dbaf30701add38a90dcbf793646d4980082b542bf45596425aa8e9e01a562bd0096dfd901b97ff835bf12f96ea848564a15dc5c334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
